name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1

    - name: gradle fetch
      run: gradle fetch
      working-directory: ./Xamarin.Android.Relinker

    - name: msbuild
      run: msbuild Relinker.sln
